spring:
  datasource:
    url: jdbc:mysql://${DB}:3306/boot_db?useUnicode=true&charaterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: admin123
  jpa:
    hibernate:
      ddl-auto: create
DB: localhost